export const Colors = {
  light: {
    background: "#F4F3EF",
    card: "#FFFFFF",
    border: "#DADADA",
    text: "#1A1A1A",
    textMuted: "#6A6A6A",
    icon: "#1A1A1A",
    primary: "#1A1A1A",
    primaryForeground: "#FFFFFF",
    secondary: "#F0EFEA",
    secondaryForeground: "#1A1A1A",
    destructive: "#FCEBEB",
    destructiveForeground: "#B84A3A",
    green: "#1A1A1A",
    red: "#B84A3A",
    foreground: "#1A1A1A",
  },
  dark: {
    background: "#0F0F0F",
    card: "#151515",
    border: "#2A2A2A",
    text: "#F2F2F2",
    textMuted: "#8C8C8C",
    icon: "#F2F2F2",
    primary: "#F2F2F2",
    primaryForeground: "#0F0F0F",
    secondary: "#1B1B1B",
    secondaryForeground: "#F2F2F2",
    destructive: "#2A1A1A",
    destructiveForeground: "#E07A5F",
    green: "#F2F2F2",
    red: "#E07A5F",
    foreground: "#F2F2F2",
  },
};
