import { themes } from "../src/constants/theme";

export const Colors = {
  light: {
    background: themes.light.background,
    card: themes.light.surface,
    border: themes.light.border,
    text: themes.light.textPrimary,
    textMuted: themes.light.textMuted,
    icon: themes.light.textPrimary,
    primary: themes.light.accent,
    primaryForeground: themes.light.accentText,
    secondary: themes.light.surfaceAlt,
    secondaryForeground: themes.light.textPrimary,
    destructive: themes.light.dangerBg,
    destructiveForeground: themes.light.warning,
    green: themes.light.accent,
    red: themes.light.warning,
    foreground: themes.light.textPrimary,
  },
  dark: {
    background: themes.dark.background,
    card: themes.dark.surface,
    border: themes.dark.border,
    text: themes.dark.textPrimary,
    textMuted: themes.dark.textMuted,
    icon: themes.dark.textPrimary,
    primary: themes.dark.accent,
    primaryForeground: themes.dark.accentText,
    secondary: themes.dark.surfaceAlt,
    secondaryForeground: themes.dark.textPrimary,
    destructive: themes.dark.dangerBg,
    destructiveForeground: themes.dark.warning,
    green: themes.dark.accent,
    red: themes.dark.warning,
    foreground: themes.dark.textPrimary,
  },
};
